package recipes;

import java.io.Serializable;

public enum Material implements Serializable {
    BAUXITE, CATERIUM_ORE, COAL, COPPER_ORE, CRUDE_OIL, PACKAGED_OIL, IRON_ORE, LIMESTONE, NITROGEN_GAS, PACKAGED_NITROGEN_GAS, RAW_QUARTZ, SAM_ORE, SULFUR, URANIUM, WATER, PACKAGED_WATER,
    CABLE, CONCRETE, COPPER_INGOT, IRON_INGOT, IRON_PLATE, IRON_ROD, REINFORCED_IRON_PLATE, SCREW, WIRE,
    COPPER_SHEET, MODULAR_FRAME, ROTOR, SMART_PLATING,
    STEEL_BEAM, STEEL_INGOT, STEEL_PIPE, VERSATILE_FRAMEWORK,
    AUTOMATED_WIRING, ENCASED_INDUSTRIAL_BEAM, HEAVY_MODULAR_FRAME, MOTOR, STATOR,
    ADAPTIVE_CONTROL_UNIT, CIRCUIT_BOARD, COMPUTER, EMPTY_CANISTER, FUEL, PACKAGED_FUEL, HEAVY_OIL_RESIDUE, PACKAGED_HEAVY_OIL_RESIDUE, MODULAR_ENGINE, PETROLEUM_COKE, PLASTIC, POLYMER_RESIN, RUBBER,
    ALUMINA_SOLUTION, PACKAGED_ALUMINA_SOLUTION, ALUMINUM_CASING, ALCLAD_ALUMINUM_SHEET, ALUMINUM_INGOT, ALUMINUM_SCRAP, ASSEMBLY_DIRECTOR_SYSTEM, BATTERY, RADIO_CONTROL_UNIT, SULFURIC_ACID, PACKAGED_SULFURIC_ACID,
    COOLING_SYSTEM, COPPER_POWDER, ELECTROMAGNETIC_CONTROL_ROD, EMPTY_FLUID_TANK, ENCASED_PLUTONIUM_CELL, ENCASED_URANIUM_CELL, FUSED_MODULAR_FRAME, HEAT_SINK, MAGNETIC_FIELD_GENERATOR, NITRIC_ACID, PACKAGED_NITRIC_ACID, NON_FISSILE_URANIUM, NUCLEAR_PASTA, PLUTONIUM_FUEL_ROD, PLUTONIUM_PELLET, PLUTONIUM_WASTE, PRESSURE_CONVERSION_CUBE, THERMAL_PROPULSION_ROCKET, TURBO_MOTOR, URANIUM_FUEL_ROD, URANIUM_WASTE,

    AI_LIMITER, BLACK_POWDER, CATERIUM_INGOT, COMPACTED_COAL, FABRIC, HIGH_SPEED_CONNECTOR, QUICKWIRE, QUARTZ_CRYSTAL, SILICA, CRYSTAL_OSCILLATOR, SUPERCOMPUTER, TURBOFUEL, PACKAGED_TURBOFUEL,
    PORTABLE_MINER, BEACON, GAS_FILTER, IODINE_INFUSED_FILTER, NOBELISK, RIFLE_CARTRIDGE, SPIKED_REBAR
}
